function [response,doExit,doCancel] = CIVM_processingMenu()

    % Present the user with a menu of options

        response = menu('Pick one of the following options:"',...
                    'Show data',...
                    'Phase Spectra',...
                    'Auto Reference',...
                    'Baseline Arguments',...
                    'Apply Processing to Dataset',...
                    'Reset phasing',...
                    'SAVE AND EXIT',...
                    '',...
                    'Cancel (do not save)');
                
    % Inform on Save and exit options
    
        doExit = false;
        doCancel = false; 
        
        if response == 7
            doExit = true;
        elseif response == 9
            doCancel = true;
        end
end